### ISSUE TITLE
GAT 2015 compile error

### ISSUE THREAD

**Issue by jeanpaulsmit** [microsoftarchive/OpenGAX#1]
First of all thanks for your efforts to build GAX/GAT for VS 2015, without it I wouldn't even start upgrading the BizTalk Software Factory to VS 2015.
However I downloaded the package, had to make some changes to the GAX (not code, just to get around the InternalsVisibleTo attribute issue) and installed it. 
Next GAT, but that one gives a compile error:

`1>------ Build started: Project: MetaGuidancePackage, Configuration: Debug Any CPU ------
1>  MetaGuidancePackage -> 
1>  MetaGuidancePackage -> 
1>  MetaGuidancePackage -> C:\Software\OpenGAX-VS2015\GAT\Src\bin\Debug\Microsoft.Practices.RecipeFramework.MetaGuidancePackage.dll
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\bofanai0.hcu\Microsoft.Practices.RecipeFramework.Build.targets(30,3): error MSB4018: The "GenerateMenuResource" task failed unexpectedly.
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\bofanai0.hcu\Microsoft.Practices.RecipeFramework.Build.targets(30,3): error MSB4018: System.NullReferenceException: Object reference not set to an instance of an object.
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\bofanai0.hcu\Microsoft.Practices.RecipeFramework.Build.targets(30,3): error MSB4018:    at Microsoft.Practices.RecipeFramework.VisualStudio.Templates.TemplateMetaData.get_ProjectFactory()
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\bofanai0.hcu\Microsoft.Practices.RecipeFramework.Build.targets(30,3): error MSB4018:    at Microsoft.Practices.RecipeFramework.VisualStudio.Templates.TemplateMetaData..ctor(String templateFileName, CommandID command, String packageName, RegistryKey registryRoot)
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\bofanai0.hcu\Microsoft.Practices.RecipeFramework.Build.targets(30,3): error MSB4018:    at Microsoft.Practices.RecipeFramework.VisualStudio.Build.GenerateMenuResource.CompileCTO(String& tempCTO)
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\bofanai0.hcu\Microsoft.Practices.RecipeFramework.Build.targets(30,3): error MSB4018:    at Microsoft.Practices.RecipeFramework.VisualStudio.Build.GenerateMenuResource.Execute()
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\bofanai0.hcu\Microsoft.Practices.RecipeFramework.Build.targets(30,3): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\bofanai0.hcu\Microsoft.Practices.RecipeFramework.Build.targets(30,3): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
`

Obviously there is an issue with my GAX version, but can you help me determining the cause?

**Comment by jelledruyts** [comment]
Do you have C++ installed with VS2015? It's needed for certain build steps and the "GenerateMenuResource" could be one of them.

Now next to that, why do you actually need to **build** GAT/GAX locally in order to upgrade your own Software Factory? You can just install it from https://github.com/MicrosoftArchive/OpenGAX/releases and then build upon the released binaries, no?

**Comment by jeanpaulsmit** [comment]
Thanks a lot for your quick reply! 
I have C++ installed so I don't know what is wrong.
Indeed you're right, I don't need the sources and actually I was looking for the released VSIX but I overlooked them. Probably still used to Codeplex ;-)
Thanks again for your great work!
